address: ':8080'
connection-string: 'postgres://go-app-server:Password1@localhost:5432/go-app-db?sslmode=disable'
queries:
  user:
    get_by_id: 'SELECT id, username, email FROM users WHERE id = $1'
    create: 'INSERT INTO users (username, email) VALUES ($1, $2) RETURNING id'
    update: 'UPDATE users SET username = $1, email = $2 WHERE id = $3'
    delete: 'DELETE FROM users WHERE id = $1 RETURNING id'
    exists_by_username: 'SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)'
    exists_by_email: 'SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)'
